version: "3.9"
networks:
  dcap-tier:
    driver: bridge

services:

  dcap-db:
    image: mysql:latest
    container_name: dcap-db
    platform: linux/amd64
    restart: always
    volumes:
      - db_data:/var/lib/mysql
      - type: bind
        source: ./mysql/docker.cnf
        target: /etc/mysql/conf.d/blog/docker.cnf
        consistency: cached
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    networks:
      - dcap-tier

  dcap-wordpress:
    depends_on:
      - dcap-db
    image: wordpress:5.8.0-fpm-alpine
    container_name: dcap-wordpress
    platform: linux/amd64
    volumes:
      - wp_data:/var/www/html
    networks:
      - dcap-tier
    restart: always
    environment:
      WORDPRESS_DB_HOST: dcap-db:3306
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ALLOW_MULTISITE', true);
        define( 'MULTISITE', true );
        define( 'SUBDOMAIN_INSTALL', false );
        #in development, ensure host file is updated to match
        define( 'DOMAIN_CURRENT_SITE', 'api.hectordiaz.pro' );
        define( 'PATH_CURRENT_SITE', '/' );
        define( 'SITE_ID_CURRENT_SITE', 1 );
        define( 'BLOG_ID_CURRENT_SITE', 1 );

  dcap-server:
    depends_on:
      - dcap-wordpress
    image: 'nginx:1.15.12-alpine'
    container_name: dcap-server
    platform: linux/amd64
    restart: unless-stopped
    networks:
      - dcap-tier
    ports:
      - "80:80"
      - '443:443'
    volumes:
      - ./nginx/snippets:/etc/nginx/snippets
      - ./nginx:/etc/nginx/conf.d
      - ../portfolio/:/var/www/
      - wp_data:/var/www/html

volumes:
  db_data:
  wp_data:

