version: "3.9"
networks:
  db-tier:
    driver: bridge

services:
  server:
    image: 'bitnami/nginx:latest'
    restart: always
    networks:
      - db-tier
    ports:
      - '80:80'
      - '443:443'
    volumes:
      - /var/www/blog/docker/nginx/snippets:/opt/bitnami/nginx/conf/snippets
      - /var/www/blog/docker/nginx:/opt/bitnami/nginx/conf/server_blocks/
      - /var/www/:/var/www/

  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    volumes:
      - wordpress_data:/var/www/blog/docker/wordpress
    networks:
      - db-tier
    ports:
      - "8000:80"
    restart: always
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
      WORDPRESS_DB_NAME: wordpress

  db:
    image: mysql:latest
    restart: always
    command: 
      --init-file /data/application/init.sql
    volumes:
      #- /var/www/blog/docker/mysql/data:/var/lib/mysql
      - /var/www/blog/docker/mysql/init.sql:/data/application/init.sql
      - type: bind
        source: /var/www/blog/docker/mysql/docker.cnf
        target: /etc/mysql/conf.d/blog/docker.cnf
        consistency: cached
    environment:
      MYSQL_ROOT_PASSWORD: somewordpress
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
    ports:
      - '3306:3306'
    networks:
      - db-tier
        
volumes:
  db_data: {}
  wordpress_data: {}
