version: "3.9"

services:

  dcap-db:
    restart: unless-stopped
    #environment:
      #MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      #MYSQL_DATABASE: ${MYSQL_DATABASE}
      #MYSQL_USER: ${MYSQL_USER}
      #MYSQL_PASSWORD: ${MYSQL_PASSWORD}

  dcap-wordpress:
    restart: unless-stopped
    environment:
      WORDPRESS_DB_NAME: ${DCAP_WP_DB_NAME}
      WORDPRESS_DB_USER: ${DCAP_WP_DB_USER}
      WORDPRESS_DB_PASSWORD: ${DCAP_WP_DB_PASSWORD}
      WORDPRESS_CONFIG_EXTRA: ${DCAP_WP_CONFIG_EXTRA}

  dcap-server:
    restart: unless-stopped
    environment:
      DCAP_BASE: ${DCAP_BASE_DOMAIN}
      DCAP_API: ${DCAP_API_DOMAIN}
      DCAP_FOLIO: ${DCAP_FOLIO_DOMAIN}
      DCAP_BLOG: ${DCAP_BLOG_DOMAIN}
      DCAP_STATIC: ${DCAP_STATIC_DOMAIN}
      ST_VID: ${SAINT_VID_DOMAIN}
      CERT_DIR: ${DCAP_CERT_DIR}
    volumes:
      - cert_data:/etc/letsencrypt
      - certs:/var/www/certs
      - type: bind
        source: ./nginx/nginx_env.sh
        target: /etc/nginx/nginx_env.sh
        consistency: cached
    command: sh -c "/etc/nginx/nginx_env.sh"

  dcap-certbot:
    depends_on:
      - dcap-wordpress
    image: certbot/certbot
    container_name: dcap-certbot
    platform: linux/amd64
    volumes:
      - cert_data:/etc/letsencrypt
      - certs:/var/www/certs
    command: certonly --webroot --webroot-path=/var/www/certs --email ${DCAP_MAIN_EMAIL} --agree-tos --no-eff-email -d ${DCAP_API_DOMAIN} -d ${DCAP_FOLIO_DOMAIN} -d ${DCAP_BLOG_DOMAIN} -d ${SAINT_VID_DOMAIN} -d ${DCAP_STATIC_DOMAIN}

volumes:
  cert_data:
  certs:


